### ISSUE TITLE
Readthedocs needs rebuilding

### ISSUE THREAD

**Issue by peleion** [spesmilo/electrum-docs#101]
Tails page updated to Version 4 referencing the now-working Electrum. 

EDIT: SomberNight made a page about sending to multiple addresses in a single transaction based on [this](https://bitcoin.stackexchange.com/questions/35686/how-do-you-send-to-multiple-addresses-by-paying-a-one-time-fee-which-wallet-sup) but I don't see it now.
EDIT AGAIN: Found it in the FAQ, looks like it was prior to the last rebuild. The only updated page right now is the Tails.

**Comment by ecdsa** [comment]
rebuilt today
