### ISSUE TITLE
Tor option suddenly disappeared

### ISSUE THREAD

**Issue by quantumx314** [spesmilo/electrum-docs#102]
I'm using Electrum 3.3.8.  In the Tool/Network/Proxy tab, I used to have a "Tor" button that I could select but it disappeared suddenly and I'm not able to get it back, even by uninstalling and reinstalling Electrum.  I'm not able to connect to my node anymore since that bug appeared.
See print screen of what I now see (only the proxy option):
![Tor option](https://user-images.githubusercontent.com/60696279/74204458-3d1b3580-4c41-11ea-9c9f-c16341c76ad3.jpg)

**Comment by SomberNight** [comment]
The option is only visible if Electrum can find a running Tor process that exposes a SOCKS proxy on port 9050 or 9150.
For example, if you have Tor Browser running.

**Comment by quantumx314** [comment]
Halleluah.  I launched a Tor browser and it indeed solved the issue, thanks!
