### ISSUE TITLE
facing problem in working with rpc

### ISSUE THREAD

**Issue by SnpGroup** [spesmilo/electrum-docs#106]
I am following doc link: https://electrum.readthedocs.io/en/latest/merchant.html?highlight=rpc

I followed steps mentioned under heading "Install Electrum-Merchant"

successfully completed this step - pip3 install electrum-merchant; and installed all dependencies successfully.

when i am performing next step - python -m electrum-merchant; i am getting following error

C:\Electrum-3.3.8>python -m electrum-merchant
Error: could not find paymentrequest_pb2.py. Create it with 'protoc --proto_path
=electrum/ --python_out=electrum/ electrum/paymentrequest.proto'

I have checked, paymentrequest_pb2.py file exists in electrum folder

Please guide me, I am stuck with development

Thanks

**Comment by ecdsa** [comment]
make sure you use python3.
I am going to rewrite this documentation for Electrum 4.0. 
I suggest you try from git master

**Comment by SnpGroup** [comment]
My operating system is windows, I have installed python3.8. 

When I tried to run it using python3 (python3 -m electrum-merchant), it's giving giving error file/command not found. 

When I check python directory, I did not find anything like python3 application there, hence I used python instead.

I try to get code from git master as per your suggestion.

Documentation will take too much time, till then my development will get stuck. Please try to provide support on ticket till then.

Thanks

**Comment by ecdsa** [comment]
electrum-merchant is deprecated and will not be used in Electrum 4.0.
That's why I am going to rewrite that documentation.

**Comment by ecdsa** [comment]
the page is now updated.
