### ISSUE TITLE
Where I can find payto / send rpc request format in doc

### ISSUE THREAD

**Issue by SnpGroup** [spesmilo/electrum-docs#108]
I have searched entire document and internet to find rpc request to send btc, but could not find any information related to this.

Please guide me, as my development got stuck.

**Comment by SomberNight** [comment]
You call it like any other command.

See the help message for it:
```
$ ./run_electrum help payto
```
Also, it's defined here in the source:
https://github.com/spesmilo/electrum/blob/21e637f5438e32dd0f6fdae17b0c908c5ab4d24b/electrum/commands.py#L611
