### ISSUE TITLE
help - no password electrum

### ISSUE THREAD

**Issue by Bitoma** [spesmilo/electrum-docs#13]
I installed electrum , it has not asked me for the password it has not shown me the seed.
I think that this has happened because probably the electum wallet during the new installation has recovered data from an old installation.
Unfortunately I have not been paying attention to this, the wallet was activated immediately and i send bitcoin to it from a bitcoin core wallet. ,...... Now my bitcoin are in the electrum wallet installed on my PC and I do not have the password and e seed.
how can I recover the bitcoins? people say that those bitcoin are lost but I can't belive it....they are in my wallet installed in my pc.......
Can you help me please.......?

thank you in advance

**Comment by ecdsa** [comment]
if you do not have the password nor the seed, then you will not be able to recover those bitcoins.

do you remember performing the old installation?
