### ISSUE TITLE
payto, individual fee is ignored

### ISSUE THREAD

**Issue by kfe908** [spesmilo/electrum-docs#149]
I would like to make a new transaction where I add an individual fee, e.g. with payto ADDR 0.000002 -f 0.000001

However, Electrum is somehow ignoring my fee.
Can anybody help how to make a transaction where I can set an individual calculated fee?

**Comment by SomberNight** [comment]
Working for me, cannot reproduce. If the difference is below 100 sats, maybe try setting
`$ ./run_electrum -o setconfig coin_chooser_output_rounding false`
