### ISSUE TITLE
cold storage watch-only screens outdated

### ISSUE THREAD

**Issue by scottj97** [spesmilo/electrum-docs#18]
The instructions for creating a watch-only wallet for cold storage show out-of-date GUI screens:

 electrum-docs/png/restore.png

The new method is:
1. select Standard wallet (**not** "Watch Bitcoin addresses"! This was very confusing to me)
2. select Use public or private keys

Then continue as before (paste xpub)

**Comment by MCTyler** [comment]
I second this, I cannot figure out if I'm creating a secure Cold Wallet or not by following these directions.

**Comment by kim3er** [comment]
I've created a pull request to update the tutorial. https://github.com/spesmilo/electrum-docs/pull/41

**Comment by scottj97** [comment]
I confirm this was fixed by PR #41
