### ISSUE TITLE
Enable TLS for docs.electrum.org

### ISSUE THREAD

**Issue by w3rs** [spesmilo/electrum-docs#35]
I understand that you can't get both TLS and custom domain for free with readthedocs.io, but I think it's essential to have traffic encryption by default. With plain HTTP, MITM (e.g. Tor exit node) could mess up with the docs and potentially direct someone to download their patched Electrum version.

This page suggest how you can set up TLS with your HTTP server: https://docs.readthedocs.io/en/latest/alternate_domains.html

Alternatively, you can just redirect to https://electrum.readthedocs.io

**Comment by ecdsa** [comment]
website now redirects to https://electrum.readthedocs.io
