### ISSUE TITLE
2FA

### ISSUE THREAD

**Issue by MudWar** [spesmilo/electrum-docs#50]
This keeps coming up! I can't add 2FA from here, please help

![capture](https://user-images.githubusercontent.com/30239655/33879098-50d56af2-df68-11e7-99e8-57c94e9a7b25.JPG)

**Comment by ecdsa** [comment]
to create a new file, enter a new file name

**Comment by bauerj** [comment]
Hey,

this repository is for issues with the documentation only. Issues with Electrum should be reported to https://github.com/spesmilo/electrum instead. 

This will be easier in a future version of Electrum due to a new wizard design: spesmilo/electrum#4069.
