### ISSUE TITLE
Electrum blocked

### ISSUE THREAD

**Issue by BrunoCrime** [spesmilo/electrum-docs#51]
From 9 dic it's so ,i don't understand , have send money on Xapo but transaction not found on blockchain ,you see Jaxx ,cause the first time return me but not send nothing , now on xapo have a transaction but not found on blockchain the one that i found are another transaction ![1ele](https://user-images.githubusercontent.com/34344740/34058243-91d39d70-e1da-11e7-94a3-4c1ef6303425.JPG)

**Comment by bauerj** [comment]
Hey,

this repository is for issues with the documentation only. Issues with Electrum should be reported to https://github.com/spesmilo/electrum instead. I assume this issue has been resolved now, if not please open a new issue there.
