### ISSUE TITLE
Unconfirmed transaction

### ISSUE THREAD

**Issue by jakieboi503** [spesmilo/electrum-docs#56]
I switched the 'fee's" in my wallet because it was trying to charge me $100 to add $50 to a site. Now my coin is still 'unconfirmed' days later..Help...
Transaction ID
339298f15882107e377c319cd994555a840d06293f3cc4c7b87fc6a17fdf280e

**Comment by Tihii0508** [comment]
1Jh2v9qPLf6oH5JrJKXz35RQahPNKCvPMF
Переведите все сюда, а потом обратно и вме будет хорошо!
