### ISSUE TITLE
Keepkey Compile Error

### ISSUE THREAD

**Issue by Satori83** [spesmilo/electrum-docs#69]
I was using Electrum 3.0.2 on OSX Sierra fine and now I get Failed to Compile Output errors when sending. Upgraded Keepkey to latest firmware too. Any known issues or fixes for this?

**Comment by SomberNight** [comment]
Please try with latest Electrum, I believe this was fixed.
Also, this is the repository for documentation, you were looking for the [main repo](https://github.com/spesmilo/electrum).
