### ISSUE TITLE
Electrum RPC authentication error.

### ISSUE THREAD

**Issue by coineralpha** [spesmilo/electrum-docs#70]
i am trying to use electrum rpc , its giving me authentication error.
i have tried user pass via basic authentication on linux bash and via php but non works.

my php code was working fine before plectrum vulnerability upgrade.
also i have tried curl on bash , but i get same error

>Error code explanation: 401 - No permission -- see authorization schemes.

i have tried

curl --data-binary '{"id":"curltext","method":"listaddresses","params":{"funded":true}}' http://test:abc@127.0.0.1:7777

and

curl --data-binary '{"id":"curltext","method":"listaddresses","params":{"funded":true}}' http://127.0.0.1:7777

and 

curl -utest  http://127.0.0.1:7777

but electrum server never accepts any authentication.

i have also tried by disabling the rpc authentication , still i get the same error

**Comment by bauerj** [comment]
Please report this to https://github.com/spesmilo/electrum in stead. This doesn't seem to be an issue with the documentation.
