### ISSUE TITLE
FAQ- What is the seed? 

### ISSUE THREAD

**Issue by JayOceans** [spesmilo/electrum-docs#82]
"The seed is a random phrase that is used to **_generate_** your private keys."
NOT "generate"
should read -
"restore" 
because -
first, private-keys are generated, 
and THEN they are BIP39ed into seed-words, right...

**Comment by bauerj** [comment]
No, it's correct. The seed is used to generate the master private keys and thus all wallet private keys.

**Comment by JayOceans** [comment]
oh, sorry!...
thanks!

**Comment by bauerj** [comment]
No worries, it takes some time to understand the concept.
