### ISSUE TITLE
Electrum merchant, payment URL not pointing to a payment request handling server

### ISSUE THREAD

**Issue by trickyriky** [spesmilo/electrum-docs#90]
Ok so i have spent the last 2 days getting electrum payments setup, and i am now well and truly stuck. I have it creating payment requests but those payments requests respond with "payment URL not pointing to a payment request handling server". 
Is there something missing from the documentation? 
Does electrum deal with running SimpleWebSocketServer? or should i be running it somehow, i have tried a few obvious things but electrum no longer complains that i need to install it, so i assume it is working.
Do i need to forward some ports?

The only thing i am not sure i have right is my apache2 setup although there could be more, please can somebody tell me how to properly convert the following nginx example to apache2 and exactly where i should be putting it? htaccess, apache2.conf.

location /payment/ {
    default_type "application/bitcoin-paymentrequest";
    alias /srv/www/payment/;
}

**Comment by bauerj** [comment]
Documentation has been extended.

**Comment by trickyriky** [comment]
<Directory /home/...path to.../req/> 
    ForceType application/bitcoin-paymentrequest
</Directory>

Correct apache config.
