### ISSUE TITLE
new wallet generated, Bitstamp says 'invalid bitcoin address.'

### ISSUE THREAD

**Issue by knlr** [spesmilo/electrum-docs#92]
I haven't used electrum in a while. I have created a new wallet. I want to withdraw bitcoins from bitstamp. I copied and pasted the address under 'receiving address' into Bitstamp. But it doesn't accept it. It does however accept the address from my older electrom wallet

**Comment by ecdsa** [comment]
bitstamp does not support segwit addresses.
they plan to add support soon, though

**Comment by SomberNight** [comment]
Please open a support ticket with them and complain about them not supporting bech32.
Stress that many other exchanges have been supporting it for a year or more.

**Comment by bidetaggle** [comment]
Hi, how is it going about that now?

**Comment by bauerj** [comment]
You need to ask them.
