### ISSUE TITLE
Tails.rst, Electrum on Tails

### ISSUE THREAD

**Issue by Bleichgesicht** [spesmilo/electrum-docs#93]
After downloading and moving the AppImage file to the Persistent folder I cannot open it by simply double-clicking it. I also enabled "execute file as program" in the properties. What am I doing wrong?

**Comment by peleion** [comment]
Are you sure you downloaded the entire file? Tors downloads can be slow - you will get this problem if the file has not been completely downloaded. Try deleting the appimage and downloading it again.

**Comment by ecdsa** [comment]
offtopic for docs
