### ISSUE TITLE
Readthedocs needs rebuilding

### ISSUE THREAD

**Issue by peleion** [spesmilo/electrum-docs#95]
The current readthedocs linked to from the main electrum.org page is two years old - dates from 2017 version 3.1. 

I imagine there are quite a lot of users that are getting outdated/inaccurate information and many (most?) users don't know to look at github for the latest. Makes Electrum look broken/unmaintained when the official documentation doesn't work.

**Comment by ecdsa** [comment]
thanks, I rebuilt it
