### ISSUE TITLE
How exactly to integrate web sockets ?

### ISSUE THREAD

**Issue by WhiteBookmark** [spesmilo/electrum-docs#96]
I have succeeded in installing electrum and running it as a daemon, it also accepts bitcoin in my website through electrum-merchant but one thing I do not understand is that how exactly to integrate web sockets ?

I did read the docs but the only information there is how to connect to a web socket server, lets suppose I make my own, **then what procedure should I follow next ?** Sockets, events, verifying, count of confirmations etc all this stuff would be done by me through custom coding or electrum can do it by itself ?

Secondly I would like to request for electrum-merchant to display the wallet address on the index.html page when viewed, not everyone use QR code or bitcoin core wallet, this can help a lot.

Thanks

**Comment by ser** [comment]
1) I think you should read electrum docs first, including merchant chapter.
2) We are planning to deliver other templates, but until they are ready, look at javscript part of index.html and just add address in there.

**Comment by WhiteBookmark** [comment]
I have read it again and so far everything works fine except for the web socket part, which I don't understand what to do, there is not enough information on how to successfully implement the websockets. JSONRPC is working fine with curl, but I need a way to know whether or not the user has paid the invoice which can be done using sockets only.

**Comment by ser** [comment]
Maybe this guide will be helpful, then? http://yz.mit.edu/wp/web-sockets-tutorial-with-simple-python-server/

**Comment by WhiteBookmark** [comment]
Well that just shows hosting a simple socket server. You mean I just need to run an empty web socket server with nothing coded inside it and electrum will take care of everything by itself ?

**Comment by ser** [comment]
If you followed electrum merchant docs, the simple socket server already works for you. The tutorial is useful to see how the javascript part is constructed.

**Comment by WhiteBookmark** [comment]
I am not sure if it is actually working or I am not doing something right. I see this message in browser console when I test a payment request:

`JQMIGRATE: Migrate is installed, version 3.0.1
index.html?id=5835f9a531:41 getJSON:success
index.html?id=5835f9a531:76 Opening WSS: wss://<Server IP Address>:7246/
index.html?id=5835f9a531:77 WebSocket connection to 'wss://<Server IP Address>:7246/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
(anonymous) @ index.html?id=5835f9a531:77`

I also noticed that it is using "wss", I did not configure https, perhaps this could be the issue ? But why is it automatically using wss (https) model, I don't need it, is there any way to let it use ws instead of wss ?

**Comment by ser** [comment]
You can't use electrum websockets without providing keys for SSL. It is clearly stated in requirements on the top of documentation chapter.

**Comment by ecdsa** [comment]
merchant documentation was updated for 4.0
websockets do not require an installation anymore
