### ISSUE TITLE
Multisig Issue: No need for 2 Multisig Wallets

### ISSUE THREAD

**Issue by skyerjoe** [spesmilo/electrum-docs#99]
**Win7
Electrum 3.3.8**

Hello 

Ive tested this many times and u dont need 2 multisig wallets for multisig transactions.

One Multisig- Wallet is enough and the other can be an normal standard legacy wallet also.

But if u use the **Cosigner Plugin** u just need 2 Multisig Wallets cause it seems that the message only appears when 2 Multisig are involved. 

Could someone confirm this ? 

If so may an slightly edit on the doc will be good 

best regards

**Comment by SomberNight** [comment]
> Ive tested this many times and u dont need 2 multisig wallets for multisig transactions.
> One Multisig- Wallet is enough and the other can be an normal standard legacy wallet also.

Please clarify what you mean. How do you create the wallet specifically?

**Comment by skyerjoe** [comment]
Hello

I've created one Multisigwallet ( Legacy) as it described in the Doc. 
and for the Cosigner i have taken a normal (Legacy) Wallet just for singing.

That works also

best regards
